<?php
// Pingdom API config
$pingdom_accounts[0]['username'] = '';
$pingdom_accounts[0]['password'] = '';
$pingdom_accounts[0]['api_key'] = '';
//$pingdom_accounts[1]['include'] = array();

//$pingdom_accounts[1]['username'] = '';
//$pingdom_accounts[1]['password'] = '';
//$pingdom_accounts[1]['api_key'] = '';
// A whitelist of checks to monitor. Leave this blank to include all checks.
//$pingdom_accounts[1]['include'] = array();

//$pingdom_accounts[1]['username'] = '';
//$pingdom_accounts[1]['password'] = '';
//$pingdom_accounts[1]['api_key'] = '';
// Leave blank to include all
//$pingdom_accounts[1]['include'] = array();

// Logging
define('LOG_LEVEL', 2);

// Checks to temporarily ignore. Must be full check name exactly.
$ignore_checks = array(
);

?>
